lib: [
  "_build/install/default/lib/cstruct-unix/META" {"META"}
  "_build/install/default/lib/cstruct-unix/opam" {"opam"}
  "_build/install/default/lib/cstruct-unix/unix_cstruct.cmi" {"unix_cstruct.cmi"}
  "_build/install/default/lib/cstruct-unix/unix_cstruct.cmx" {"unix_cstruct.cmx"}
  "_build/install/default/lib/cstruct-unix/unix_cstruct.cmt" {"unix_cstruct.cmt"}
  "_build/install/default/lib/cstruct-unix/unix_cstruct.cmti" {"unix_cstruct.cmti"}
  "_build/install/default/lib/cstruct-unix/unix_cstruct.mli" {"unix_cstruct.mli"}
  "_build/install/default/lib/cstruct-unix/unix_cstruct.ml" {"unix_cstruct.ml"}
  "_build/install/default/lib/cstruct-unix/cstruct_unix.cma" {"cstruct_unix.cma"}
  "_build/install/default/lib/cstruct-unix/cstruct_unix.cmxa" {"cstruct_unix.cmxa"}
  "_build/install/default/lib/cstruct-unix/cstruct_unix.a" {"cstruct_unix.a"}
  "_build/install/default/lib/cstruct-unix/cstruct_unix.cmxs" {"cstruct_unix.cmxs"}
  "_build/install/default/lib/cstruct-unix/cstruct-unix.dune" {"cstruct-unix.dune"}
]
doc: [
  "_build/install/default/doc/cstruct-unix/README.md"
]
