lib: [
  "_build/install/default/lib/cstruct-async/META" {"META"}
  "_build/install/default/lib/cstruct-async/opam" {"opam"}
  "_build/install/default/lib/cstruct-async/async_cstruct.cmi" {"async_cstruct.cmi"}
  "_build/install/default/lib/cstruct-async/async_cstruct.cmx" {"async_cstruct.cmx"}
  "_build/install/default/lib/cstruct-async/async_cstruct.cmt" {"async_cstruct.cmt"}
  "_build/install/default/lib/cstruct-async/async_cstruct.cmti" {"async_cstruct.cmti"}
  "_build/install/default/lib/cstruct-async/async_cstruct.mli" {"async_cstruct.mli"}
  "_build/install/default/lib/cstruct-async/async_cstruct.ml" {"async_cstruct.ml"}
  "_build/install/default/lib/cstruct-async/async_cstruct.cma" {"async_cstruct.cma"}
  "_build/install/default/lib/cstruct-async/async_cstruct.cmxa" {"async_cstruct.cmxa"}
  "_build/install/default/lib/cstruct-async/async_cstruct.a" {"async_cstruct.a"}
  "_build/install/default/lib/cstruct-async/async_cstruct.cmxs" {"async_cstruct.cmxs"}
  "_build/install/default/lib/cstruct-async/cstruct-async.dune" {"cstruct-async.dune"}
]
doc: [
  "_build/install/default/doc/cstruct-async/README.md"
]
