lib: [
  "_build/install/default/lib/cstruct/META" {"META"}
  "_build/install/default/lib/cstruct/opam" {"opam"}
  "_build/install/default/lib/cstruct/cstruct.cmi" {"cstruct.cmi"}
  "_build/install/default/lib/cstruct/cstruct.cmx" {"cstruct.cmx"}
  "_build/install/default/lib/cstruct/cstruct.cmt" {"cstruct.cmt"}
  "_build/install/default/lib/cstruct/cstruct.cmti" {"cstruct.cmti"}
  "_build/install/default/lib/cstruct/cstruct.mli" {"cstruct.mli"}
  "_build/install/default/lib/cstruct/cstruct.ml" {"cstruct.ml"}
  "_build/install/default/lib/cstruct/cstruct.cma" {"cstruct.cma"}
  "_build/install/default/lib/cstruct/libcstruct_stubs.a" {"libcstruct_stubs.a"}
  "_build/install/default/lib/cstruct/cstruct.cmxa" {"cstruct.cmxa"}
  "_build/install/default/lib/cstruct/cstruct.a" {"cstruct.a"}
  "_build/install/default/lib/cstruct/cstruct.cmxs" {"cstruct.cmxs"}
  "_build/install/default/lib/cstruct/cstruct.dune" {"cstruct.dune"}
  "_build/install/default/lib/cstruct/cstruct.js"
]
doc: [
  "_build/install/default/doc/cstruct/README.md"
]
stublibs: [
  "_build/install/default/lib/stublibs/dllcstruct_stubs.so"
]
