lib: [
  "_build/install/default/lib/dns-async/META" {"META"}
  "_build/install/default/lib/dns-async/opam" {"opam"}
  "_build/install/default/lib/dns-async/async_dns_resolver.cmi" {"async_dns_resolver.cmi"}
  "_build/install/default/lib/dns-async/async_dns_resolver.cmx" {"async_dns_resolver.cmx"}
  "_build/install/default/lib/dns-async/async_dns_resolver.cmt" {"async_dns_resolver.cmt"}
  "_build/install/default/lib/dns-async/async_dns_resolver.cmti" {"async_dns_resolver.cmti"}
  "_build/install/default/lib/dns-async/async_dns_resolver.mli" {"async_dns_resolver.mli"}
  "_build/install/default/lib/dns-async/async_dns_resolver.ml" {"async_dns_resolver.ml"}
  "_build/install/default/lib/dns-async/async_dns_resolver_unix.cmi" {"async_dns_resolver_unix.cmi"}
  "_build/install/default/lib/dns-async/async_dns_resolver_unix.cmx" {"async_dns_resolver_unix.cmx"}
  "_build/install/default/lib/dns-async/async_dns_resolver_unix.cmt" {"async_dns_resolver_unix.cmt"}
  "_build/install/default/lib/dns-async/async_dns_resolver_unix.cmti" {"async_dns_resolver_unix.cmti"}
  "_build/install/default/lib/dns-async/async_dns_resolver_unix.mli" {"async_dns_resolver_unix.mli"}
  "_build/install/default/lib/dns-async/async_dns_resolver_unix.ml" {"async_dns_resolver_unix.ml"}
  "_build/install/default/lib/dns-async/dns_async.cma" {"dns_async.cma"}
  "_build/install/default/lib/dns-async/dns_async.cmxa" {"dns_async.cmxa"}
  "_build/install/default/lib/dns-async/dns_async.a" {"dns_async.a"}
  "_build/install/default/lib/dns-async/dns_async.cmxs" {"dns_async.cmxs"}
  "_build/install/default/lib/dns-async/dns-async.dune" {"dns-async.dune"}
]
doc: [
  "_build/install/default/doc/dns-async/README.md"
  "_build/install/default/doc/dns-async/LICENSE.md"
  "_build/install/default/doc/dns-async/CHANGES.md"
]
