lib: [
  "_build/install/default/lib/dns-lwt-unix/META" {"META"}
  "_build/install/default/lib/dns-lwt-unix/opam" {"opam"}
  "_build/install/default/lib/dns-lwt-unix/dig_unix.cmi" {"dig_unix.cmi"}
  "_build/install/default/lib/dns-lwt-unix/dig_unix.cmx" {"dig_unix.cmx"}
  "_build/install/default/lib/dns-lwt-unix/dig_unix.cmt" {"dig_unix.cmt"}
  "_build/install/default/lib/dns-lwt-unix/dig_unix.ml" {"dig_unix.ml"}
  "_build/install/default/lib/dns-lwt-unix/dns_resolver_unix.cmi" {"dns_resolver_unix.cmi"}
  "_build/install/default/lib/dns-lwt-unix/dns_resolver_unix.cmx" {"dns_resolver_unix.cmx"}
  "_build/install/default/lib/dns-lwt-unix/dns_resolver_unix.cmt" {"dns_resolver_unix.cmt"}
  "_build/install/default/lib/dns-lwt-unix/dns_resolver_unix.cmti" {"dns_resolver_unix.cmti"}
  "_build/install/default/lib/dns-lwt-unix/dns_resolver_unix.mli" {"dns_resolver_unix.mli"}
  "_build/install/default/lib/dns-lwt-unix/dns_resolver_unix.ml" {"dns_resolver_unix.ml"}
  "_build/install/default/lib/dns-lwt-unix/dns_server_unix.cmi" {"dns_server_unix.cmi"}
  "_build/install/default/lib/dns-lwt-unix/dns_server_unix.cmx" {"dns_server_unix.cmx"}
  "_build/install/default/lib/dns-lwt-unix/dns_server_unix.cmt" {"dns_server_unix.cmt"}
  "_build/install/default/lib/dns-lwt-unix/dns_server_unix.cmti" {"dns_server_unix.cmti"}
  "_build/install/default/lib/dns-lwt-unix/dns_server_unix.mli" {"dns_server_unix.mli"}
  "_build/install/default/lib/dns-lwt-unix/dns_server_unix.ml" {"dns_server_unix.ml"}
  "_build/install/default/lib/dns-lwt-unix/dns_lwt_unix.cma" {"dns_lwt_unix.cma"}
  "_build/install/default/lib/dns-lwt-unix/dns_lwt_unix.cmxa" {"dns_lwt_unix.cmxa"}
  "_build/install/default/lib/dns-lwt-unix/dns_lwt_unix.a" {"dns_lwt_unix.a"}
  "_build/install/default/lib/dns-lwt-unix/dns_lwt_unix.cmxs" {"dns_lwt_unix.cmxs"}
  "_build/install/default/lib/dns-lwt-unix/dns-lwt-unix.dune" {"dns-lwt-unix.dune"}
]
doc: [
  "_build/install/default/doc/dns-lwt-unix/README.md"
  "_build/install/default/doc/dns-lwt-unix/LICENSE.md"
  "_build/install/default/doc/dns-lwt-unix/CHANGES.md"
]
