lib: [
  "_build/install/default/lib/dns-lwt/META" {"META"}
  "_build/install/default/lib/dns-lwt/opam" {"opam"}
  "_build/install/default/lib/dns-lwt/dns_resolver.cmi" {"dns_resolver.cmi"}
  "_build/install/default/lib/dns-lwt/dns_resolver.cmx" {"dns_resolver.cmx"}
  "_build/install/default/lib/dns-lwt/dns_resolver.cmt" {"dns_resolver.cmt"}
  "_build/install/default/lib/dns-lwt/dns_resolver.cmti" {"dns_resolver.cmti"}
  "_build/install/default/lib/dns-lwt/dns_resolver.mli" {"dns_resolver.mli"}
  "_build/install/default/lib/dns-lwt/dns_resolver.ml" {"dns_resolver.ml"}
  "_build/install/default/lib/dns-lwt/dns_server.cmi" {"dns_server.cmi"}
  "_build/install/default/lib/dns-lwt/dns_server.cmx" {"dns_server.cmx"}
  "_build/install/default/lib/dns-lwt/dns_server.cmt" {"dns_server.cmt"}
  "_build/install/default/lib/dns-lwt/dns_server.cmti" {"dns_server.cmti"}
  "_build/install/default/lib/dns-lwt/dns_server.mli" {"dns_server.mli"}
  "_build/install/default/lib/dns-lwt/dns_server.ml" {"dns_server.ml"}
  "_build/install/default/lib/dns-lwt/mdns_responder.cmi" {"mdns_responder.cmi"}
  "_build/install/default/lib/dns-lwt/mdns_responder.cmx" {"mdns_responder.cmx"}
  "_build/install/default/lib/dns-lwt/mdns_responder.cmt" {"mdns_responder.cmt"}
  "_build/install/default/lib/dns-lwt/mdns_responder.cmti" {"mdns_responder.cmti"}
  "_build/install/default/lib/dns-lwt/mdns_responder.mli" {"mdns_responder.mli"}
  "_build/install/default/lib/dns-lwt/mdns_responder.ml" {"mdns_responder.ml"}
  "_build/install/default/lib/dns-lwt/dns_lwt.cma" {"dns_lwt.cma"}
  "_build/install/default/lib/dns-lwt/dns_lwt.cmxa" {"dns_lwt.cmxa"}
  "_build/install/default/lib/dns-lwt/dns_lwt.a" {"dns_lwt.a"}
  "_build/install/default/lib/dns-lwt/dns_lwt.cmxs" {"dns_lwt.cmxs"}
  "_build/install/default/lib/dns-lwt/dns-lwt.dune" {"dns-lwt.dune"}
]
doc: [
  "_build/install/default/doc/dns-lwt/README.md"
  "_build/install/default/doc/dns-lwt/LICENSE.md"
  "_build/install/default/doc/dns-lwt/CHANGES.md"
]
