lib: [
  "_build/install/default/lib/mirage-dns/META" {"META"}
  "_build/install/default/lib/mirage-dns/opam" {"opam"}
  "_build/install/default/lib/mirage-dns/dns_resolver_mirage.cmi" {"dns_resolver_mirage.cmi"}
  "_build/install/default/lib/mirage-dns/dns_resolver_mirage.cmx" {"dns_resolver_mirage.cmx"}
  "_build/install/default/lib/mirage-dns/dns_resolver_mirage.cmt" {"dns_resolver_mirage.cmt"}
  "_build/install/default/lib/mirage-dns/dns_resolver_mirage.cmti" {"dns_resolver_mirage.cmti"}
  "_build/install/default/lib/mirage-dns/dns_resolver_mirage.mli" {"dns_resolver_mirage.mli"}
  "_build/install/default/lib/mirage-dns/dns_resolver_mirage.ml" {"dns_resolver_mirage.ml"}
  "_build/install/default/lib/mirage-dns/dns_server_mirage.cmi" {"dns_server_mirage.cmi"}
  "_build/install/default/lib/mirage-dns/dns_server_mirage.cmx" {"dns_server_mirage.cmx"}
  "_build/install/default/lib/mirage-dns/dns_server_mirage.cmt" {"dns_server_mirage.cmt"}
  "_build/install/default/lib/mirage-dns/dns_server_mirage.cmti" {"dns_server_mirage.cmti"}
  "_build/install/default/lib/mirage-dns/dns_server_mirage.mli" {"dns_server_mirage.mli"}
  "_build/install/default/lib/mirage-dns/dns_server_mirage.ml" {"dns_server_mirage.ml"}
  "_build/install/default/lib/mirage-dns/mdns_resolver_mirage.cmi" {"mdns_resolver_mirage.cmi"}
  "_build/install/default/lib/mirage-dns/mdns_resolver_mirage.cmx" {"mdns_resolver_mirage.cmx"}
  "_build/install/default/lib/mirage-dns/mdns_resolver_mirage.cmt" {"mdns_resolver_mirage.cmt"}
  "_build/install/default/lib/mirage-dns/mdns_resolver_mirage.cmti" {"mdns_resolver_mirage.cmti"}
  "_build/install/default/lib/mirage-dns/mdns_resolver_mirage.mli" {"mdns_resolver_mirage.mli"}
  "_build/install/default/lib/mirage-dns/mdns_resolver_mirage.ml" {"mdns_resolver_mirage.ml"}
  "_build/install/default/lib/mirage-dns/mirage_dns.cma" {"mirage_dns.cma"}
  "_build/install/default/lib/mirage-dns/mirage_dns.cmxa" {"mirage_dns.cmxa"}
  "_build/install/default/lib/mirage-dns/mirage_dns.a" {"mirage_dns.a"}
  "_build/install/default/lib/mirage-dns/mirage_dns.cmxs" {"mirage_dns.cmxs"}
  "_build/install/default/lib/mirage-dns/mirage-dns.dune" {"mirage-dns.dune"}
]
doc: [
  "_build/install/default/doc/mirage-dns/README.md"
  "_build/install/default/doc/mirage-dns/LICENSE.md"
  "_build/install/default/doc/mirage-dns/CHANGES.md"
]
